name = "subly"
main = "worker/src/index.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "subly"
database_id = "92571f48-4924-48f6-a6fc-b8a72f6706c0"

# 每小时触发一次检查
[triggers]
crons = ["0 * * * *"]

[vars]
ENVIRONMENT = "production"
